# Generated by Django 5.2.7 on 2025-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='address',
        ),
        migrations.AddField(
            model_name='dealer',
            name='city',
            field=models.CharField(default='Agra', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default='Agra', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='state',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
