# Generated by Django 5.2.7 on 2025-10-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_phone_dealer_contact_remove_dealer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('date_of_sale', models.DateField()),
                ('last_service_date', models.DateField()),
                ('service_kms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dealer')),
            ],
        ),
    ]
