# Generated by Django 5.2.7 on 2025-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_servicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
