# Generated by Django 5.2.7 on 2025-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_labourservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='services',
            field=models.ManyToManyField(blank=True, to='portal.labourservice'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
