# Generated by Django 5.2.7 on 2025-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_servicerecord_services_servicerecord_total_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=10, unique=True)),
                ('part_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
