# Generated by Django 5.2.7 on 2025-10-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='components',
            field=models.ManyToManyField(blank=True, to='portal.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='part_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.component')),
            ],
        ),
    ]
