# Generated by Django 5.2.7 on 2025-10-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_servicerecord_components_alter_component_part_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_received_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.component'),
        ),
    ]
