# Generated by Django 5.2.7 on 2025-10-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_inventory_dealer_inventory_last_received_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='part_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='component',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.vehiclemodel'),
        ),
    ]
