# Generated by Django 5.2.7 on 2025-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_vehiclemodel_alter_component_part_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='model',
        ),
        migrations.AlterField(
            model_name='component',
            name='part_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
