# Generated by Django 5.2.7 on 2025-10-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_component_model_alter_component_part_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='part_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
