# Generated by Django 5.2.7 on 2025-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_testride'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('dealership_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city_name', models.CharField(max_length=50)),
                ('reason_for_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_visit', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('staff_behaviour', models.CharField(max_length=20)),
                ('services_rating', models.CharField(max_length=20)),
                ('purchase_experience', models.CharField(max_length=20)),
                ('lounge_experience', models.CharField(max_length=20)),
                ('access_lounge', models.CharField(max_length=5)),
                ('schemes_explained', models.CharField(max_length=5)),
                ('queries_resolved', models.CharField(max_length=5)),
                ('benefits_discussed', models.CharField(max_length=5)),
                ('overall_rating', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
