# Generated by Django 5.2.7 on 2025-10-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('date_of_quotation', models.DateField()),
                ('ex_showroom', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hypothecation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cow_cess', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dealer')),
            ],
        ),
    ]
