# Generated by Django 5.2.7 on 2025-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDIInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('dealer_code', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('vin', models.CharField(max_length=50)),
                ('battery_no', models.CharField(max_length=50)),
                ('charger_no', models.CharField(max_length=50)),
                ('motor_no', models.CharField(max_length=50)),
                ('controller_no', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
