# Generated by Django 5.2.7 on 2025-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_pdiinspection_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='battery_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='jc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='motor_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
