# Generated by Django 5.2.7 on 2025-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_servicerecord_battery_number_servicerecord_jc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
