# Generated by Django 5.2.7 on 2025-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_servicerecord_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerToDealerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_dealer_name', models.CharField(max_length=100)),
                ('primary_gst', models.CharField(max_length=50)),
                ('primary_code', models.CharField(max_length=50)),
                ('primary_phone', models.CharField(max_length=20)),
                ('primary_address', models.TextField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_dealer_name', models.CharField(max_length=100)),
                ('secondary_gst', models.CharField(max_length=50)),
                ('secondary_code', models.CharField(max_length=50)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('secondary_address', models.TextField()),
                ('secondary_email', models.EmailField(max_length=254)),
                ('date_of_purchase', models.DateField()),
                ('model_name', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=50)),
                ('battery_number', models.CharField(max_length=50)),
                ('chasis_number', models.CharField(max_length=50)),
                ('motor_number', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_rep_name', models.CharField(max_length=100)),
                ('purchase_rep_mobile', models.CharField(max_length=20)),
                ('purchase_rep_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealerToDealerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_dealer_name', models.CharField(max_length=100)),
                ('primary_gst', models.CharField(max_length=50)),
                ('primary_code', models.CharField(max_length=50)),
                ('primary_phone', models.CharField(max_length=20)),
                ('primary_address', models.TextField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_dealer_name', models.CharField(max_length=100)),
                ('secondary_gst', models.CharField(max_length=50)),
                ('secondary_code', models.CharField(max_length=50)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('secondary_address', models.TextField()),
                ('secondary_email', models.EmailField(max_length=254)),
                ('date_of_sale', models.DateField()),
                ('model_name', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=50)),
                ('battery_number', models.CharField(max_length=50)),
                ('chasis_number', models.CharField(max_length=50)),
                ('motor_number', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_rep_name', models.CharField(max_length=100)),
                ('sales_rep_mobile', models.CharField(max_length=20)),
                ('sales_rep_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
