# Generated by Django 5.2.7 on 2025-11-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_dealertodealerpurchase_dealertodealersale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealertodealerpurchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='dealertodealersale',
            options={'ordering': ['-id']},
        ),
    ]
