# Generated by Django 5.2.7 on 2025-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_dealertodealerpurchase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTagPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('service_order_no', models.CharField(max_length=50)),
                ('warranty_type', models.CharField(max_length=50)),
                ('model_no', models.CharField(max_length=50)),
                ('odo_reading', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_no', models.CharField(max_length=100)),
                ('customer_sale_date', models.DateField(blank=True, null=True)),
                ('part_description', models.CharField(max_length=200)),
                ('part_serial_number', models.CharField(max_length=100)),
                ('customer_complaint', models.TextField(blank=True, null=True)),
                ('diagnostic_details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('material_code', models.CharField(max_length=100)),
                ('reason_for_replacement', models.TextField(blank=True, null=True)),
                ('last_service_details', models.TextField(blank=True, null=True)),
                ('customer_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('technical_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyPartPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=50)),
                ('boxes', models.IntegerField(default=0)),
                ('total_weight', models.CharField(max_length=50)),
                ('approx_weight', models.CharField(max_length=100)),
                ('material_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
