# Generated by Django 5.2.7 on 2025-11-11 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_alter_pdiinspection_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdiinspection',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.dealer'),
        ),
    ]
