# Generated by Django 5.2.7 on 2025-11-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_pdiinspection_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtagpart',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.dealer'),
        ),
        migrations.AddField(
            model_name='failedtagpart',
            name='dealer_id_val',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='failedtagpart',
            name='dealer_name_val',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.dealer'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='dealer_id_val',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='dealer_name_val',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warrantypartpickup',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.dealer'),
        ),
        migrations.AddField(
            model_name='warrantypartpickup',
            name='dealer_id_val',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warrantypartpickup',
            name='dealer_name_val',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
